module;
#include <dcomp.h>
#include <dcomptypes.h>

export module PGUI.UI.DComp.DCompEnums;

export namespace PGUI::UI::DComp
{
	enum class BitmapInterpolationMode
	{
		NearestNeighbor = DCOMPOSITION_BITMAP_INTERPOLATION_MODE_NEAREST_NEIGHBOR,
		Linear = DCOMPOSITION_BITMAP_INTERPOLATION_MODE_LINEAR,
		Inherit = DCOMPOSITION_BITMAP_INTERPOLATION_MODE_INHERIT
	};

	enum class BorderMode
	{
		Soft = DCOMPOSITION_BORDER_MODE_SOFT,
		Hard = DCOMPOSITION_BORDER_MODE_HARD,
		Inherit = DCOMPOSITION_BORDER_MODE_INHERIT
	};

	enum class CompositeMode
	{
		SourceOver = DCOMPOSITION_COMPOSITE_MODE_SOURCE_OVER,
		DestinationInvert = DCOMPOSITION_COMPOSITE_MODE_DESTINATION_INVERT,
		MinBlend = DCOMPOSITION_COMPOSITE_MODE_MIN_BLEND,
		Inherit = DCOMPOSITION_COMPOSITE_MODE_INHERIT
	};

	enum class BackFaceVisibility
	{
		Visible = DCOMPOSITION_BACKFACE_VISIBILITY_VISIBLE,
		Hidden = DCOMPOSITION_BACKFACE_VISIBILITY_HIDDEN,
		Inherit = DCOMPOSITION_BACKFACE_VISIBILITY_INHERIT
	};

	enum class OpacityMode
	{
		Layer = DCOMPOSITION_OPACITY_MODE_LAYER,
		Multiply = DCOMPOSITION_OPACITY_MODE_MULTIPLY,
		Inherit = DCOMPOSITION_OPACITY_MODE_INHERIT
	};

	enum class DepthMode
	{
		Tree = DCOMPOSITION_DEPTH_MODE_TREE,
		Spatial = DCOMPOSITION_DEPTH_MODE_SPATIAL,
		Sorted = DCOMPOSITION_DEPTH_MODE_SORTED,
		Inherit = DCOMPOSITION_DEPTH_MODE_INHERIT
	};
}
